// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Our Story"
          quote="Founded on October 1, 2023, United Team was built with one mission: to deliver honest, transparent, and professional dispatch services that help carriers succeed."
          author="Management Team"
          role="United Team Founders"
          imageSrc="http://img.b2bpic.net/free-photo/female-staff-working-airport-terminal_107420-85075.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
