// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contact Us"
          text="Ready to scale your Amazon Relay operations? Get in touch with United Team today."
          primaryButton={{
            text: "Request Dispatch Service",
            href: "#contact-form",
          }}
          secondaryButton={{
            text: "Call Now",
            href: "tel:+15136534606",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
