// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesImageBento
          tag="Why Choose Us"
          title="Performance-Driven Dispatch"
          description="Drivers trust United Team because we focus on higher rates, honest communication, and professional support."
          items={[
            {
              title: "Higher Rates",
              description: "Focusing on your bottom line.",
              imageSrc: "http://img.b2bpic.net/free-photo/aerial-view-elevated-motorway-along-lam-takhong-lake-thailand_1308-189326.jpg",
            },
            {
              title: "Fast Response",
              description: "Quick communication.",
              imageSrc: "http://img.b2bpic.net/free-photo/warehouse-woman-worker-confidently-walking-through-large-warehouse-storage-center-organizing-distribution_342744-1517.jpg",
            },
            {
              title: "Dedicated Support",
              description: "Always here for you.",
              imageSrc: "http://img.b2bpic.net/free-photo/man-with-medical-mask-working-radio-station_23-2148815355.jpg",
            },
            {
              title: "Route Optimization",
              description: "Optimized every mile.",
              imageSrc: "http://img.b2bpic.net/free-photo/autonomous-delivery-robot_35913-2154.jpg",
            },
            {
              title: "Long-Term Partners",
              description: "Building lasting success.",
              imageSrc: "http://img.b2bpic.net/free-photo/management-warehouse-profile-woman-with-long-red-hair-protective-helmet-looking-tablet-screen-walking-along-warehouse-aisle_259150-56882.jpg",
            },
            {
              title: "Safety First",
              description: "Compliance monitored.",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-man-holding-smartphone_23-2149426490.jpg",
            },
            {
              title: "24/7 Operations",
              description: "Working for you always.",
              imageSrc: "http://img.b2bpic.net/free-photo/professional-trucker-driver-hugging-his-truck-cabin-loving-his-job_342744-1270.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
