// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
          tag="United Team Logistics"
          title="Professional Amazon Relay Dispatch Services Across the United States"
          description="United Team provides reliable 24/7 Amazon Relay dispatch services, helping carriers and owner-operators maximize revenue through strategic load planning and route optimization."
          primaryButton={{
            text: "Get Started",
            href: "#CtaSection",
          }}
          secondaryButton={{
            text: "About Us",
            href: "#about",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/modern-white-freight-truck-transporting-cargo-winter-highway-logistics-truck-road_169016-71714.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/orange-trucks-road_1127-184.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-black-man-writing-notes-build-new-development-strategy-managing-data-analytics_482257-136351.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/truck-digital-art-illustration_23-2151650079.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/technological-futuristic-holograms-logistics-means-transport_23-2151663015.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/delivery-van-loaded-with-boxes-warehouse_23-2151998679.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
