// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Calendar, Clock, Truck, Users } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Our Growth"
          title="Dispatch By The Numbers"
          description="Trusted by partner carriers across the nation."
          metrics={[
            {
              icon: Calendar,
              title: "Founded",
              value: "2023",
            },
            {
              icon: Users,
              title: "Dispatchers",
              value: "16",
            },
            {
              icon: Truck,
              title: "Drivers/Operators",
              value: "30+",
            },
            {
              icon: Clock,
              title: "Availability",
              value: "24/7",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
