/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";

const members = [
  {
    name: "Alex Johnson",
    role: "Co-Founder",
    imageSrc: "http://img.b2bpic.net/free-photo/young-attractive-man-glassess-is-standing-near-workplace-office-he-wears-blue-shirt-dark-jacket-laptop-hand-he-is-looking-camera_197531-519.jpg"
  },
  {
    name: "Sarah Smith",
    role: "Operations Manager",
    imageSrc: "http://img.b2bpic.net/free-photo/online-remote-courses-bored-student-home_23-2148552277.jpg"
  },
  {
    name: "Mike Davis",
    role: "Dispatcher",
    imageSrc: "http://img.b2bpic.net/free-photo/modern-company-manager-workplace-bright-office_1163-5267.jpg"
  },
  {
    name: "Elena Ross",
    role: "Safety Compliance",
    imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-call-center-agent-dealing-with-unhappy-customers_482257-117856.jpg"
  },
  {
    name: "David Chen",
    role: "Night Shift Dispatcher",
    imageSrc: "http://img.b2bpic.net/free-photo/confident-businessman-smiling-outside-office-building_107420-74332.jpg"
  },
  {
    name: "Emily White",
    role: "Customer Support",
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-positive-businesswoman_1098-3531.jpg"
  },
  {
    name: "James Wilson",
    role: "Fleet Coordinator",
    imageSrc: "http://img.b2bpic.net/free-photo/smiling-woman-posing-with-crossed-arms_23-2148336911.jpg"
  },
  {
    name: "Jessica Taylor",
    role: "Logistics Analyst",
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-cheerful-manager-sunny-day_1139-417.jpg"
  },
  {
    name: "Michael Brown",
    role: "Route Optimizer",
    imageSrc: "http://img.b2bpic.net/free-photo/elegant-business-woman-front-glass-building_23-2147704436.jpg"
  },
  {
    name: "Amanda Martinez",
    role: "Carrier Relations",
    imageSrc: "http://img.b2bpic.net/free-photo/businessman-with-tablet_1098-135.jpg"
  },
  {
    name: "Robert Anderson",
    role: "Weekend Dispatcher",
    imageSrc: "http://img.b2bpic.net/free-photo/empowered-business-woman-working-city_23-2149322942.jpg"
  },
  {
    name: "Olivia Thomas",
    role: "Billing Specialist",
    imageSrc: "http://img.b2bpic.net/free-photo/smiling-businessmen-their-office_1098-81.jpg"
  },
  {
    name: "William Jackson",
    role: "Tracking Specialist",
    imageSrc: "http://img.b2bpic.net/free-photo/cheerful-professional-partners-posing-photo-smiling-looking-camera-african-american-successful-office-employer-caucasian-businesswoman-taking-selfie-teamwork-business-concept_74855-6842.jpg"
  },
  {
    name: "Sophia Garcia",
    role: "Account Manager",
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-half-face-business-woman_23-2148336844.jpg"
  },
  {
    name: "Richard Lee",
    role: "Compliance Officer",
    imageSrc: "http://img.b2bpic.net/free-photo/business-woman-with-glasses-front-glass-building_23-2147704438.jpg"
  },
  {
    name: "Isabella Clark",
    role: "Onboarding Specialist",
    imageSrc: "http://img.b2bpic.net/free-photo/closeup-smiling-senior-business-man-relaxing_1262-2369.jpg"
  },
  {
    name: "Thomas Lewis",
    role: "Dispatch Supervisor",
    imageSrc: "http://img.b2bpic.net/free-photo/middle-aged-businesswoman-smiling_1262-21181.jpg"
  }
];

type TeamMember = {
  name: string;
  role: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TeamInline = () => (
  <section aria-label="Team section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Meet Our Dispatchers"}</p>
        </div>

        <TextAnimation
          text={"United Team"}
          variant={"slide-up"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Our professionals are dedicated to your carrier success."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="fade-blur">
        <GridOrCarousel >
          {members.map((member) => (
            <div key={member.name} className="relative aspect-4/5 card rounded">
              <div className="relative w-full h-full rounded overflow-hidden">
                <ImageOrVideo imageSrc={member.imageSrc} videoSrc={member.videoSrc} />

                <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex items-center justify-between gap-4 xl:gap-5 2xl:gap-6 p-4 xl:p-5 2xl:p-6 card backdrop-blur-sm rounded">
                  <span className="text-xl font-semibold leading-snug truncate">{member.name}</span>
                  <div className="px-3 py-2 text-sm primary-button text-primary-cta-text rounded">
                    <p className="truncate">{member.role}</p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function TeamSection() {
  return (
    <div data-webild-section="team" data-section="team" id="team">
      <TeamInline />
    </div>
  );
}
