// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from '@/components/sections/team/TeamOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamOverlayCards
          tag="Meet Our Dispatchers"
          title="The United Team"
          description="Our professionals are dedicated to your carrier success."
          members={[
            {
              name: "Alex Johnson",
              role: "Senior Dispatcher",
              imageSrc: "http://img.b2bpic.net/free-photo/young-attractive-man-glassess-is-standing-near-workplace-office-he-wears-blue-shirt-dark-jacket-laptop-hand-he-is-looking-camera_197531-519.jpg",
            },
            {
              name: "Sarah Smith",
              role: "Operations Manager",
              imageSrc: "http://img.b2bpic.net/free-photo/online-remote-courses-bored-student-home_23-2148552277.jpg",
            },
            {
              name: "Mike Davis",
              role: "Load Planner",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-company-manager-workplace-bright-office_1163-5267.jpg",
            },
            {
              name: "Elena Ross",
              role: "Safety Compliance",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-call-center-agent-dealing-with-unhappy-customers_482257-117856.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
