// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Testimonials"
          title="Trusted by Carriers"
          description="Feedback from partners we support."
          testimonials={[
            {
              name: "John Doe",
              role: "Owner Operator",
              quote: "United Team increased my load rates and efficiency. Highly recommended.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-businessman-happy-expression_1194-1681.jpg",
            },
            {
              name: "Jane Miller",
              role: "Fleet Manager",
              quote: "The most transparent and professional dispatch service I have worked with.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-businesswoman-prepared-meeting_1098-2188.jpg",
            },
            {
              name: "Sam Roberts",
              role: "Driver",
              quote: "Excellent communication and route planning every single day.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/man-working-as-truck-driver_23-2151489776.jpg",
            },
            {
              name: "Lisa Wang",
              role: "Carrier Partner",
              quote: "They truly care about maximizing my revenue. Outstanding support.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/truck-driver-opening-reservoir-tank-refuel-truck-holding-thumbs-up_342744-1274.jpg",
            },
            {
              name: "David Brown",
              role: "Owner Operator",
              quote: "Reliable 24/7 service that has stabilized our business operations.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/mid-adult-engineer-using-touchpad-communicating-with-african-american-worker-about-product-reports-industrial-building_637285-4098.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
